export default {
  drawer: require('../assets/images/drawer.png'),
  metric: require('../assets/images/metric.png'),
  bell: require('../assets/images/bell.png'),
  calendar: require('../assets/images/calendar.png'),
  info: require('../assets/images/info.png'),
  overview: require('../assets/images/overview.png'),
  send: require('../assets/images/send.png'),
  profile: require('../assets/images/profile.jpeg'),
  arrowdown: require('../assets/images/arrowdown.png'),
  arrowup: require('../assets/images/arrowup.png'),
  airplane: require('../assets/images/airplane.jpeg'),
  logout: require('../assets/images/logout.png'),
  logo: require('../assets/images/logo.jpeg'),
  back: require('../assets/images/back.png'),
  dummyimage: require('../assets/images/dummyimage.jpeg'),
};
