export default {
  welcome: 'Welcome',
  loginAsGuest: 'Login as guest!',
  getStarted: 'Get Started',
  blogs: 'Blogs',
  hello: 'Hello',
  liveMetrics: 'Live Metrics',
  dashboards: 'Dashboards',
  overview: 'Overview',
  calender: 'Calender',
  scheduleActions: 'Schedule Actions',
  liveAlerts: 'Live Alerts',
  latest: 'Latest',
  archived: 'Archived',
  documentation: 'Documentation',
  noDataFound: 'No Data Found',
  reports: 'Reports',
  needHelp: 'Need Help?',
  somethingWentWrong: 'Something went wrong',
  edit: 'Edit',
  delete: 'Delete',
  logout: 'Logout',
};
