export default {
  welcome: 'Welcome',
  loginAsGuest: 'Login as guest!',
  getStarted: 'Get Started',
  blogs: 'Blogs',
  hello: 'Hello',
  liveMetrics: 'Live Metrics',
  dashboards: 'Dashboards',
  overview: 'Overview',
  calender: 'Calender',
  scheduleActions: 'Schedule Actions',
  liveAlerts: 'Live Alerts',
  latest: 'Latest',
  archived: 'Archived',
  documentation: 'Documentation',
  noDataFound: 'No Data Found',
  reports: 'Reports',
  needHelp: 'Need Help?',
  somethingWentWrong: 'Something went wrong',
  edit: 'Edit',
  delete: 'Delete',
  logout: 'Logout',
  title: 'Title',
  description: 'Description',
  typeSomething: 'Type Something...',
  update: 'Update',
  pleaseEnterTitle: 'Please enter the title',
  pleaseEnterDescription: 'Please enter the Description',
  postUpdated: 'Post has been updated successfully',
  postDeleted: 'Post has been deleted successfully',
};
